### ISSUE TITLE
Support multiple bike tag regions

### ISSUE THREAD

**Issue by adamdavis40208** [KenEucker/biketag-website#1]
Hey Ken,

The bike tag idea was stolen from /r/chicago: it'd be cool to support some of the more popular bike subs (and it'll get you some more traffic).

Sweet idea!

**Comment by KenEucker** [comment]
Super happy to report that this has finally been implemented on the website!

Since the creation of this project, we've had this expansion in mind, and recently someone in Denver has shown an interest in starting up a biketag game in their city. That enthusiasm has driven this feature to the forefront this month and I'm excited to see the potential for more biketag games in more cities!

In addition to this feature rolling out we now have a landing page for the homepage that links to the "Supported Regions". Coming soon will be the ability to apply for the biketag ambassadorship program to spin-up/kick-off a biketag.org site for anyone who wants to be an ambassador and help us in spreading the game of biketag!

While traffic is picking up I'm happy to see that this feature both allows us to scale with the single server that is running biketag.org as well as allows us to deploy individual instances of the app for any individual biketag regions. So for a longer running game like the one in Austin, Texas (with almost 1,000 tags now!), that might require more from the server, we can deploy a single instance on a separate server just for that region to keep the app performant.

Thanks for creating our first issue @adamdavis40208! We hope you consider this closed for now and welcome any feedback you want to provide.
