### ISSUE TITLE
Discovery of BikeTag Games on the internet between 2018 and 2021 (until EOL)

### ISSUE THREAD

**Issue by ellenwest** [KenEucker/biketag-website#119]
The goal of this ticket is to capture the presence of BikeTag on ~Reddit~ the Internet.

Searching "site: Reddit.com BikeTag" and using Reddit's site search of "BikeTag" helped me surface these games/attempts at starting games of BikeTag: 

1. (Houston) BikeHouston: https://www.reddit.com/r/bikehouston/comments/3i4g1h/bike_tag_1/
2. (San Francisco) BABike: https://www.reddit.com/r/BAbike/comments/cciaa5/bike_tag_19/
3. (Chicago) ChiBike: https://www.reddit.com/r/chibike/comments/3iew6o/bike_tag_rules/
4. (Austin) BikingATX: https://www.reddit.com/r/BikingATX/
5. (Los Angeles) BikeLA: https://www.reddit.com/r/BikeLA/wiki/phototag 
6. (Madison, WI) BikingMad: https://www.reddit.com/r/BikingMad/comments/hah8h8/bike_tag_44/
7. (San Jose) SanJose:  https://www.reddit.com/r/SanJose/comments/dd03sa/bike_tag_7_greetings_from_san_jose/
8. [Asking if there is interest, 3 months ago] (NYC) NYCBike: https://www.reddit.com/r/NYCbike/comments/fce6re/interest_in_starting_bike_tag_to_show_off_our/
9.  [Rules posted 2 months ago] MiamiBiking: https://www.reddit.com/r/miamibiking/comments/fxyz3w/bike_tag_rules/
10. (Washington DC) BikeDC: https://www.reddit.com/r/bikedc/comments/fbzuza/bike_tag_5/
11. (Buffalo, NY) BuffaloBike: https://www.reddit.com/r/BuffaloBike/comments/8nxns8/bike_tag_3/
12. (Global/themed?) reddit.com/r/FixedGearBicycle/comments/afmq0z/biketag2019_tag_2_hang_in_there_baby/ 

....
13. (San Antonio, TX) BikeSATX: https://www.reddit.com/r/bikesatx/comments/hi4y69/bike_tag_1/
14. (Eugene, OR) eugenebiketag: https://www.reddit.com/r/eugenebiketag/

... and here are our cities using BikeTag.org:
1. (Portland) CyclePDX: https://www.reddit.com/r/CyclePDX/ 
2. (Seattle) SeattleBike: https://www.reddit.com/r/seattlebike/comments/hfx1hi/bike_tag_9/
3. (Indianapolis) BikeIN: https://www.reddit.com/r/bikeIN/comments/hfxpfx/biketag_30/
4. (Denver) CycleDenver: https://www.reddit.com/r/CycleDenver/
5. [No BT posts yet](Omaha) OmahaMetroCycling: https://www.reddit.com/r/OmahaMetroCycling/ 
6. [No BT posts yet] (St. Louis) StLouisBiking: https://www.reddit.com/r/StLouisBiking/
7. (Vancouver) vancouvercycling: https://www.reddit.com/r/vancouvercycling/
8. (Vienna) Radwien: https://www.reddit.com/r/radwien/comments/hfrj7d/bike_tag_6/

In chatting with @KenEucker, we decided it could be interesting to start a spreadsheet where we track basic information like:
* Game actively being played (Y/N)
* Rules link (many subreddits refer to ChiBike for rules)
* First post/intro post link 
* Supported (i.e. uses BikeTag.org)
 
cc: @evan-white @JackieSul 

If you know of any other subreddits playing BT, add 'em to the list!

**Comment by ellenwest** [comment]
I'd like to expand this list to include all games of BikeTag that can be found online. I stumbled upon a game of Twin Cities BikeTag that lives on Facebook: https://www.facebook.com/groups/398836313619169/about if we don't already have that list.

**Comment by KenEucker** [comment]
Just discovered BikeSATX (San Antonio) started a game 12 days ago! https://www.reddit.com/r/bikesatx/comments/hi4y69/bike_tag_1/

**Comment by KenEucker** [comment]
Found games on Facebook today, all of these appear to be a spinoff of the "Twin Cities Photo Tag" group:

"Twin Cities Photo Tag"
https://www.facebook.com/groups/398836313619169

"Saint Paul Bicycle Photo Tag"
https://www.facebook.com/groups/1783924781693044/

"Minneapolis Bicycle Photo Speed Tag"
https://www.facebook.com/groups/273612940072777/

"MSP Bicycle Photo EASY TAG"
https://www.facebook.com/groups/MspBicyclePhotoEasyTag/

"Twin Cities Photo Tag -- Beyond the Loop"
https://www.facebook.com/groups/998487573918338/

"Woodbury Bicycle Photo Tag"
https://www.facebook.com/groups/1123783271324423/

"Mac Groveland Family Bicycle Photo Tag"
https://www.facebook.com/groups/macgrovelandfamilybiketag/

"Pittsburg Bike Tag"
https://www.facebook.com/groups/2537124303269151/

"Seattle Bike Tag"
https://www.facebook.com/SeattleBikeTag/

"Fgm BikeTag"
https://www.facebook.com/fgm.biketag

"Marseille BIKE TAG"
https://www.facebook.com/Marseille-BIKE-TAG-Par-Fixed-Gear-Marseille-130473837121915/

**Comment by KenEucker** [comment]
One just started in Eugene, Oregon, a month ago! 

https://www.reddit.com/r/eugenebiketag/

**Comment by KenEucker** [comment]
Not Reddit, but here's a game of BikeTag in Brussels on Facebook:
https://www.facebook.com/BrusselsBikeTag/

An older game that may not be played, actively. The group is private.
https://he-il.facebook.com/groups/MidDownBikeTag/


It appears that there is a larger number of BikeTag games on Facebook than we currently have an understanding of. It would be good if someone could spend some time searching on Facebook and trying to catalog all of the found games.

**Comment by KenEucker** [comment]
Also not Reddit, but the forum LFGSS has a range of games for the UK:
https://www.lfgss.com/search/?q=bike%20tag+inTitle:true+sort:date

(Brighton) https://www.lfgss.com/conversations/169251/?offset=1250#comment15686328 
(Edinburgh) https://www.lfgss.com/conversations/353455/?offset=25#comment15697668
(Middlesbrough) https://www.lfgss.com/conversations/202063/?offset=25#comment15442733
(Birmingham) https://www.lfgss.com/conversations/191089/?offset=75#comment15422030
(Newcastle) https://www.lfgss.com/conversations/186556/?offset=950#comment14413204
(Norwich) https://www.lfgss.com/conversations/227575/?offset=675#comment14225307
(Oxford) https://www.lfgss.com/conversations/214176/?offset=150#comment13920965
(Alternate Reality) https://www.lfgss.com/conversations/239333/?offset=225#comment14026629

It would be cool to see if we can import games from this forum in some way. Maybe the forum platform has an API?

**Comment by KenEucker** [comment]
I'd like to have a deliverable for this ticket be links to all active games and an associated ticket for creating non-playable views of those games that are not yet supported in any way (forums that aren't Reddit, facebook, Instagram, etc...). That way we are tracking all of the current games and providing whatever information/links we can to all known games of BikeTag.

**Comment by KenEucker** [comment]
These are the games that were started, in order, by the BikeTag Project over the life of this `biketag-website` project;

NOTE:
~games~ == games that were prompted by someone reaching out and asking that a game be created but not followed up on (by the person who prompted it)

* == games that are 100% stale at tag 1, meaning the BikeTag Ambassador hasn't introduced it to a community 

[game] == games that were started before integrating with biketag.org

--------------------------------------
--                     Launch                        --
--------------------------------------
1. [Portland, Oregon] - February 2018
--------------------------------------
--   Games launched after the first   --
--------------------------------------
2. Denver, Colorado - 2020
3. [Indianapolis, Indiana] - 2020
4. Seattle, Washington - 2020

~5. Omaha, Nebraska~
~6. St Louis, Missouri~

7. Vancouver, Washington - 2020
8. Vienna, Austria - 2020

~9. Eugene, Oregon~

10. [Miami, Florida] - 2020
--------------------------------------
--  After supporting more than one  --
--------------------------------------
~11. Glasgow, Scotland~

* 12. Inverness, Scotland - 2020

13. Comox Valley, British Columbia - 2020
--------------------------------------
--  After GCN video appearance.      --
--------------------------------------
14. Cowichan Valley, British Columbia - 2020
15. Abbotsford, British Columbia - 2020

~16. Oklahoma City, Oklahoma~
~17. Saarbrücken, Germany~
~18. Rome, Italy~

* 19. Phoenix, Arizona - 2020

~20. Tulsa, Oklahoma~
~21. Edmonton, Alberta, Canada~

22. Hull, England - 2020

* 23. Charlotte, North Carolia - 2020

24. Ottawa, Canada - 2020

~25. Dresden, Germany~

26. Montreal, Canada - 2020

~27. San Jose, California~

* 28. Emporia, Kansas - 2020

~29. Tokyo, Japan~

* 30. Kansas City, Kansas - 2020

31. Peak District, England - 2020
32. Paris, France - 2020
33. Victoria, British Columbia - 2020

~34. Lexington, Kentucky~

35. Tolouse, Italy - 2020
36. Harrisburg, Pennsylvania - 2020

~37. Boston, Massachusetts~

38. Islamabad, Pakistan - 2020

~39. Prague, Czech Republic~
~40. Hamburg, Germany~
~41. Berlin, Germany~

* 42. Bellingham, Washington - 2021

43. Chilliwack, British Columbia - 2021
44. Dayton, Ohio - 2021
45. Peoria, Illinois - 2021
46. Bangalore, India - 2021
47. New Haven, Connecticut - 2021
48. Gatineau, Québec, Canada - 2021
49. Isle Of Wight, England - 2021
50. Seacoast, New Hampshire - 2021

~51. Cardiff, Wales~

52. Prince George, British Columbia - 2021
53. Calgary, Canada - 2021

~54. Toronto, Canada~
~55. Santa Barbara, California~
~56. Boise, Idaho~
~57. Grand Prairie, Texas~

58. London Ontario, Canada - 2021

~59. Cape Ann, Massachusetts~

60. Bangor, Maine - 2021

~61. Salem, Oregon~
~62. Provincetown, Massachusetts~
~63. Northshore, Massachusetts~

* 64. 3city, Poland - 2021

65. Ventura, California - 2021
66. Ljubljana, Slovenia - 2021

~67. Oahu, Hawaii~

--------------------------------------
--  33 games of BikeTag successfully launched since 2018 --
--------------------------------------
