### ISSUE TITLE
Hints with parentheses don't display

### ISSUE THREAD

**Issue by AndrewPardoe** [KenEucker/biketag-website#134]
See the current hint on http://seattle.biketag.org/#hint. It doesn't show. Note that it's round #24. 

The hint does show on the Imgur backing store: https://imgur.com/NHcAadO

NB: I'm speculating as to parentheses being the issue. I can't exactly test this easily--I've been unable to build the repo.

**Comment by KenEucker** [comment]
@AndrewPardoe I just now saw this! Sorry for the late response. Thanks for pointing this out!

It looks like we might need to change our schema for data in the description of imgur images because parenthesis are commonly used in hints. With this solution, I would like there to be a mechanism created for updating all tags (in case we need to make similar changes in the future).

This is something we can do in the future, and we can manually edit any tags with parenthesis in the hint if need be in the meantime.

**Comment by KenEucker** [comment]
I think this is resolved but could use some more testing, @AndrewPardoe .

**Comment by AndrewPardoe** [comment]
If I ever get a tag again, I'll include parens!

**Comment by KenEucker** [comment]
I believe this works now!

![Screen Shot 2021-06-15 at 1 15 56 PM](https://user-images.githubusercontent.com/1720267/122117606-e9dc6880-cddb-11eb-998c-9f635b780547.png)
