### ISSUE TITLE
Only part of username is taken for image overlay and hint

### ISSUE THREAD

**Issue by SievaFliesAlone** [KenEucker/biketag-website#219]
When I played the last round, I typed in my username: **Anibyl**
However, it wasn't handled properly:
<details> 
  <summary>Proof found</summary>

![image](https://user-images.githubusercontent.com/790717/142339917-65c950a2-57c9-4d8b-9791-a3db626548e0.png)

</details>
<details> 
  <summary>New location</summary>

![image](https://user-images.githubusercontent.com/790717/142339922-9179e966-9942-42b2-ae03-9a0b85f7e58f.png)

</details>
<details> 
  <summary>Hint</summary>

![image](https://user-images.githubusercontent.com/790717/142340161-c4a53061-787f-4232-ae02-2c83d35646a0.png)

</details>

https://vancouver.biketag.org/ 533 (proof) and 534 (new location)

**Comment by KenEucker** [comment]
This happened on your post previous to this one as well, my regular expressions must not like your name for some reason. Thank you for creating this issue, @anibyl!

**Comment by SievaFliesAlone** [comment]
Usually it's fine, but sometimes it's not.

Also, I'm pleasantly surprised by how fast you replied to the issue, this has never happened to me on github :smile: :+1:

**Comment by KenEucker** [comment]
Wow, okay... This is embarrassing...

It's literally because `by` is in your name, and our template is such that by precedes the players name. The code is seeing the "by" in your name and thinking it's the end of the template for the biketag post and then grabbing what is after that, which is "l".

I just so happened to be chatting with someone and working on BikeTag at the moment. Oh, also these biketag projects are linked with our Slack channel so I saw the post there first. ;)

**Comment by KenEucker** [comment]
Hoping that this is no longer an issue moving forward with the new BikeTag App project. This biketag-website project is now sunsetting.
