### ISSUE TITLE
BikeTag 2.0

### ISSUE THREAD

**Issue by CriminallyNegligent** [KenEucker/biketag-website#245]
Not sure if this is the right place for this comment, but I've tried to use the new app twice now, on different devices, and although it seemed like everything went ok, the round didn't load and I had to use the website.

**Comment by KenEucker** [comment]
@CriminallyNegligent what name are you using for your tags?


On the current site, tags are immediately added to each round after you hit submit. This was always due to a technical limitation and forces this team (me) to deal with any and all issues after something is already displayed and/or cross posted to other social sites.

With the new app, after you submit a new BikeTag post to the round, your tag waits there until it is either auto posted after 15 minutes or the BikeTag Ambassador approves the tag, depending on the configuration of the game.

When using the new app, please wait for your tag to posted.

**Comment by CriminallyNegligent** [comment]
OK, I probably just didn't wait long enough.  The first time I tried (a
week or two ago) I used u/CriminallyNegligent because the app said the name
I had been using, "the dynamic duo,"  was already taken (probably by me,
but I couldn't figure out how to claim it), so yesterday I just used
"dynamic duo."  But when it didn't post, I reposted using the website and
my regular UN.  Next time I'll give it some more time, and let you know if
I have a problem.

Thanks for helping out!

**Comment by KenEucker** [comment]
@CriminallyNegligent you are dynamic duo? I can help make sure it works for your profile moving forward but I'm curious if you have ever logged into the new app? That is the only way that specific names are protected like you're saying. If you were seeing that issue but had never logged in then it might just be an older bug that I know we have since corrected.

**Comment by CriminallyNegligent** [comment]
I can't actually figure out how to log in.  Don't see any menu option for
it...??

**Comment by KenEucker** [comment]
https://portland.biketag.io/#/login

**Comment by CriminallyNegligent** [comment]
Somehow, the end of the hint for the bike tag I posted today (#642) got cut
off.  To try to fix it, I tried "finding" it using another name
(u/CriminallyNegligent -- which I feel I have been😣), and reposting a new
tag (#643).  I'm sure at this point you were thoroughly confused, so the
new tag didn't appear right away, and I tried so I tried again (#644, which
I thought could post as Dynamic Duo, but I guess I was still logged out, so
it came up as the second post for u/CriminallyNegligent).  This time I was
sure I'd posted the complete hint, but again it appeared cut off.  So I
decided to write to see if you could fix it (though in the interim I tried
one more time, switching names again).  It may be that this new post will
have the hint correctly (I'm not waiting for it to appear), but, if not,
here's how it should read:

Steven (sic) donated three cans of chile and 7 bottles of water here.
> (Hope you'll donate too!)


Update:  Because I just kept switching images too, I seem to have
completely confused things, because now tag #642 is showing up again, only
with the name Criminally Negligent (and still the cut-off hint).  I'm sorry
to have made such a mess of things;  my only excuse is that, at 74, I'm not
quite as sharp as I used to be.  I'm hoping you can delete everything after
tag #641 and I'll try reposting.  But perhaps you can also see if there's
some reason at your end why it's cutting off the full hints?

Sorry for the mess -- thanks for your (I hope) patience --

Jill Hinckley
the distaff half of the Dynamic Duo

**Comment by KenEucker** [comment]
@CriminallyNegligent Please stop.

If you need some information corrected you can simply send us and email to support@biketag.org. Creating multiple submissions is not the way to correct information and it adds a lot of extra work to my day when I might not have the ability to chase after you and remove the duplicates you're creating.

**Comment by CriminallyNegligent** [comment]
When I was entering the hint for tag #580, my thumb slipped mid-edit.  I'd
like it to read "It's *not a *lucky roll of the dice but still a winner."
Can you either make the correction or delete the whole tag so that I can
repost?

Thanks --
Jill
(the distaff half of the Dynamic Duo)
