### ISSUE TITLE
Content: Create Wikipedia article about Bike Tag

### ISSUE THREAD

**Issue by ellenwest** [KenEucker/biketag-website#39]
We can base our draft on the history and mission.

**Comment by ellenwest** [comment]
We have a draft set up in Wikipedia.

**Comment by ellenwest** [comment]
We need to submit a new Wikipedia draft using a non-bike tag alias.

**Comment by KenEucker** [comment]
We tried creating a BikeTag Wikipedia page but I don't really know how to edit Wikipedia and I put a lot of good information in there, but they deleted it because I created it using an account I created with our biketag email address.

Can someone please create a Wikipedia page about the game of BikeTag? Our researched history of the game is on biketag.bike:

https://biketag.bike/timeline/

That would be awesome!

**Comment by KenEucker** [comment]
Other things to check out:
https://github.com/KenEucker/biketag-website/issues/119




https://github.com/keneucker/biketag-api
https://github.com/keneucker/biketag-app
https://github.com/keneucker/biketag-vue
