### ISSUE TITLE
Create tag queue

### ISSUE THREAD

**Issue by ellenwest** [KenEucker/biketag-website#63]
A tag will go into the tag queue when it is in 'pending' status to allow us to review it.

**Comment by KenEucker** [comment]
Thoughts on this:

The form uploader should still upload to imgur, and instead of inserting "#230 tag by" we could set the description to be "[queued:230-1] tag by". Then, once the image is approved we can set the approved one to "#230 tag by" and the rest can be set to "[#230-2" or "[#230-3" depending on how many people made it into the queue. This approach still allows the images to go directly to imgur and for the app to continue to function while the next tag awaits approval.

**Comment by KenEucker** [comment]
Instead of the previous idea for a solution to the queue, I've come up with something that will work out well:

Each region will have a main album and a queue album. Using the tagit form, images are uploaded to the queue album. Email notifications are sent to the admins once a queued tag has been proceeded by a new mystery tag. 

This allows the app and main album to remain on the current tag until an ambassador is able to validate and post the new tag. Tags are then moved from the queue album to the main album. 

We can also use this strategy for the retagging feature described in #93 by adding a third album for retagged mystery tags.

**Comment by KenEucker** [comment]
The queue now exists in the new BikeTag App.

This biketag-website project is now sunsetting.
